id: factory
name: My factory

materials:
  - id: material1
    name: Material1
  - id: material2
    name: Material2

consumables:
  - id: consumable1
    name: Consumable1
  - id: consumable2
    name: Consumable2

products:
  - id: product1
    name: Product1

containers:
  - id: materialcontainer
    name: MaterialContainer(Material1)
    content: material1
    capacity: 100
  - id: materialcontainer2
    name: MaterialContainer(Material2)
    content: material2
    capacity: 100
  - id: consumablecontainer
    name: ConsumableContainer(Consumable1)
    content: consumable1
    capacity: 100
  - id: productcontainer
    name: ProductContainer(Product1)
    content: product1

boms:
  - id: bom1
    name: "My bill of material"
    materials:
      - id: material1
        consumption: 5
      - id: material2
        consumption: 10
    products:
      - id: product1
        quantity: 10

  - id: bom2
    name: "My bill of material 2"
    materials:
      - id: material1
        consumption: 2
      - id: material2
        consumption: 2.5
    consumables:
      - id: consumable1
        consumption: 2
    products:
      - id: product1
        quantity: 1

programs:
  - id: program1
    name: Program1
    bom: bom1
  - id: program2
    name: Program2
    bom: bom2

schedules:
  - id: schedule1
    name: Schedule
    blocks:
      - name: Cron(8:30, 1)
        cron: 30 8 * * *
        duration-hours: 1
        action:
          name: switch-program
          kwargs:
            program_id: program1
      - name: Cron(24 at 06:00, M)
        cron: 00 06 24 * *
        duration-hours: 24
        priority: -1
        action:
          name: maintenance
      - name: Cron(12:00, 1)
        cron: 00 12 1-31/2 * *
        duration-hours: 1.5
        action:
          name: switch-program
          kwargs:
            program_id: program1
      - name: Cron(12:00, 2)
        cron: 00 12 2-30/2 * *
        duration-hours: 1.5
        action:
          name: switch-program
          kwargs:
            program_id: program2

maintenance:
  - id: maintenance1
    name: Maintenance

machines:
  - id: machine1
    name: Machine
    schedule: schedule1
    programs: [program1, program2]
    default-program: program1
    containers:
      [
        materialcontainer,
        materialcontainer2,
        consumablecontainer,
        productcontainer,
      ]
    maintenance: maintenance1

operators:
  - id: operator1
    name: John
    machine: machine1
